---
- name: Machine setup
  hosts: localhost
  become: false
  connection: local
  gather_facts: true
  vars:
    GITHUB_USERNAME: "walterclementsjr"
    rpm_key_list:
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    copr_repos:
      - pgdev/ghostty
      - atim/lazygit

  tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_user_id }}"

    - name: Importing RPM GPG keys
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: "{{ item }}"
      loop: "{{ rpm_key_list }}"

    - name: Enable RPM Fusion Free and Nonfree repositories
      become: true
      ansible.builtin.dnf:
        name:
          - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
          - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present

    - name: Importing COPR repos
      become: true
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: "{{ item }}"
      loop: "{{ copr_repos }}"

    - name: Install devtool
      become: true
      tags: devtool
      ansible.builtin.dnf:
        name:
          - btop
          - chromium
          - curl
          - emacs
          - fastfetch
          - fd-find
          - ffmpeg-free
          - firefox
          - fzf
          - gcc
          - gcc-c++
          - gh
          - ghostty
          - git
          - lazygit
          - make
          - meld
          - neovim
          - nvtop
          - podman
          - ripgrep
          - stow
          - tealdeer
          - tmux
          - valgrind
          - virt-manager
          - yt-dlp
          - zsh
        state: present

    - name: Install the 'Development tools' package group
      become: true
      ansible.builtin.dnf:
        name: '@Development Tools'
        state: present

    - name: Install user packages
      become: true
      tags: tool
      ansible.builtin.dnf:
        name:
          - calibre
          - flatpak
          - lutris
          - qbittorrent
          - steam
        state: present

    - name: Download ohmyzsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/home/{{ remote_regular_user }}/install.sh"
        mode: '0755'

    - name: Install ohmyzsh
      ansible.builtin.script:
        cmd: "/home/{{ remote_regular_user }}/install.sh"

    - name: Installing Tmux plugins manager
      ansible.builtin.git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: "~/.tmux/plugins/tpm"

    - name: Install DNF plugins core
      become: true
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker repo
      become: true
      ansible.builtin.yum_repository:
        name: docker
        description: Docker repo
        baseurl: "https://download.docker.com/linux/fedora/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable"
        gpgkey: "https://download.docker.com/linux/fedora/gpg"
        gpgcheck: true
        enabled: true

    - name: Install Docker
      become: true
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add Docker group
      become: true
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      become: true
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: docker
        append: true

    - name: Add Flathub remote repository
      become: true
      shell:
        cmd: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - com.obsproject.Studio
          - org.videolan.VLC
          - md.obsidian.Obsidian
          - io.podman_desktop.PodmanDesktop
        state: present

